"""The Journal — situations and thoughts before they become frameworks. Edit here, then run tools/build.py.

Her master brief (2026-09): drawn from her own LinkedIn writing, rewritten for the site, never pasted. No
hashtags, no engagement questions, no "comment below"; an entry does not have to end in a lesson.

An entry: slug (its page is journal/<slug>/), date (EN, ES), title (EN, ES), story — paragraphs as (EN, ES) —
and an optional margin: ((EN, ES) text, optional (EN, ES) source). Newest first. Months come from the post
dates in her LinkedIn export (13 September 2026); nothing is dated beyond what the export shows.
"""
ENTRIES = [
    {"slug": "on-learning-to-sit-still",
     "date": ("4 September 2026", "4 de septiembre de 2026"),
     "title": ("On learning to sit still", "Sobre aprender a quedarse quieta"),
     "story": [
         ("I have never been good at stopping.", "Nunca he sabido detenerme."),
         ("Once I start something it is very hard for me to put it down, which sounds like a strength in a job interview and is mostly not one.",
          "Cuando empiezo algo me cuesta mucho soltarlo, lo que suena a virtud en una entrevista de trabajo y casi nunca lo es."),
     ]},
    # her iteration (2026-09-14): entries that explain one concept she works with, told through the object, each
    # with a drawing that carries meaning (build.py JVISUALS). Not SEO, not a course, not legal advice. A story item
    # may be a paragraph (EN, ES), a list of short lines, or {"q": [...]} — questions, optionally led by a term.
    {"slug": "a-subdivision-begins-as-one-shape",
     "date": ("Notes · 2026", "Notas · 2026"),
     "title": ("A subdivision begins as one shape", "Una subdivisión empieza como una sola forma"),
     "story": [
         ("A subdivision begins as one shape.", "Una subdivisión empieza como una sola forma."),
         ("Then the questions start cutting into it.", "Después las preguntas empiezan a recortarla."),
         {"q": [("Road", "Vía", "Does every lot have legal, usable access?", "¿Cada lote tiene un acceso legal y utilizable?"),
                ("Frontage", "Frente", "Does each lot meet the frontage it needs?", "¿Cada lote cumple el frente que necesita?"),
                ("Topography", "Topografía", "Where can a road actually go?", "¿Por dónde puede ir de verdad una vía?"),
                ("Water", "Agua", "How is each lot served?", "¿Cómo se abastece cada lote?"),
                ("Sewer or septic", "Alcantarillado o séptico", "What density does that allow?", "¿Qué densidad permite eso?"),
                ("Drainage", "Drenaje", "Where does the water go?", "¿A dónde va el agua?"),
                ("Soil", "Suelo", "What can the ground actually support?", "¿Qué puede soportar de verdad el terreno?"),
                ("Regulation", "Normativa", "What does the county permit?", "¿Qué permite el condado?"),
                ("Market", "Mercado", "What lot, and what home, is actually moving?", "¿Qué lote, y qué casa, se está vendiendo de verdad?"),
                ("Cost", "Costo", "What does the infrastructure do to the basis?", "¿Qué le hace la infraestructura a la base de costo?"),
                ("Exit", "Salida", "Who ultimately buys the lots?", "¿Quién compra los lotes al final?")]},
         ("Every answer takes something away from the original shape.", "Cada respuesta le quita algo a la forma original."),
         ("The acreage never survives intact.", "El área nunca sobrevive intacta."),
         ("What remains is the project.", "Lo que queda es el proyecto."),
     ],
     "margin": (("This is how I approach the problem. It is not a rule for anyone else’s land.", "Así es como yo abordo el problema. No es una regla para la tierra de nadie más."),)},
    {"slug": "a-joint-venture-is-not-one-deal",
     "date": ("Notes · 2026", "Notas · 2026"),
     "title": ("A joint venture is not one deal", "Un joint venture no es un solo negocio"),
     "story": [
         ("It is several incentives sharing one project.", "Son varios incentivos compartiendo un solo proyecto."),
         ("A landowner. Capital. An operator or developer. Contractors. Whoever buys at the end.", "Un propietario. El capital. Un operador o desarrollador. Los contratistas. Quien compre al final."),
         ("Each brings something different, and cash, risk, control, work and upside do not move between them the same way.",
          "Cada uno aporta algo distinto, y el dinero, el riesgo, el control, el trabajo y la ganancia no se mueven igual entre ellos."),
         {"q": [("Who contributes what?", "¿Quién aporta qué?"), ("Who funds what?", "¿Quién financia qué?"), ("Who controls which decisions?", "¿Quién controla qué decisiones?"),
                ("Who gets paid first?", "¿Quién cobra primero?"), ("Who carries the development risk?", "¿Quién carga el riesgo del desarrollo?"),
                ("What happens if the timeline changes?", "¿Qué pasa si cambian los tiempos?"), ("How is the upside divided?", "¿Cómo se reparte la ganancia?"),
                ("How is the downside allocated?", "¿Cómo se asigna la pérdida?")]},
         ("These are the questions I want answered before I trust the structure.", "Estas son las preguntas que quiero respondidas antes de confiar en la estructura."),
     ],
     "margin": (("Not legal advice, and not a template. Each venture’s own documents decide how it works.", "No es asesoría legal ni una plantilla. Los documentos de cada acuerdo deciden cómo funciona."),)},
    {"slug": "a-contract-can-change-hands",
     "date": ("Notes · 2026", "Notas · 2026"),
     "title": ("A contract can change hands without the project staying the same", "Un contrato puede cambiar de manos sin que el proyecto siga siendo el mismo"),
     "story": [
         ("On paper, the agreement can look almost identical.", "En el papel, el acuerdo puede verse casi idéntico."),
         ("An original party. A contract. A seller. Then a new party enters.", "Una parte original. Un contrato. Un vendedor. Luego entra una parte nueva."),
         ("Broadly, an assignment passes along rights under the contract, and the original party may still be responsible. A novation replaces a party altogether, and it needs everyone’s consent.",
          "A grandes rasgos, una cesión transfiere derechos del contrato, y la parte original puede seguir siendo responsable. Una novación reemplaza a una parte por completo, y necesita el consentimiento de todos."),
         ("The paper may look similar. The people, the responsibilities and the risk around it have changed.",
          "El papel puede parecerse. Las personas, las responsabilidades y el riesgo a su alrededor cambiaron."),
         {"q": [("Who consented, and to what?", "¿Quién consintió, y a qué?"), ("What moved: rights, obligations, or both?", "¿Qué se movió: derechos, obligaciones o ambos?"),
                ("Who is responsible if something goes wrong?", "¿Quién responde si algo sale mal?"), ("Did the economics change?", "¿Cambió la economía del negocio?"),
                ("What should counsel, title and the other transaction professionals review?", "¿Qué deberían revisar los abogados, la compañía de títulos y los demás profesionales de la transacción?")]},
     ],
     "margin": (("Specific legal treatment depends on the agreement and the jurisdiction. Not legal advice.", "El tratamiento legal específico depende del acuerdo y de la jurisdicción. No es asesoría legal."),)},
    {"slug": "the-deal-that-should-not-work",
     "date": ("August 2026", "agosto 2026"),
     "title": ("The deal that should not work", "El negocio que no debería funcionar"),
     "story": [
         ("A seller was asking too much for a piece of land that almost worked.", "Un vendedor pedía demasiado por un terreno que casi funcionaba."),
         ("Walking away would have been the easy part. Anyone can find the flaw in a deal and leave.",
          "Retirarse habría sido lo fácil. Cualquiera puede encontrarle la falla a un negocio e irse."),
         ("So I started from the other end: what a builder would pay for a finished lot, minus everything it would take to get there. That was the ceiling, and the room to move.",
          "Así que empecé por el otro extremo: lo que un constructor pagaría por un lote terminado, menos todo lo que costaría llegar ahí. Ese era el techo, y el margen para moverse."),
         ("Then the structure. Seller financing. A staged takedown. A price tied to entitlement milestones.",
          "Después, la estructura. Financiación del vendedor. Compra por etapas. Un precio atado a los hitos de los permisos."),
         ("Some deals that look dead come back to life in the capital stack. Not all of them should. If the market does not want the product, no structure saves it.",
          "Algunos negocios que parecen muertos reviven en la estructura de capital. No todos deberían. Si el mercado no quiere el producto, ninguna estructura lo salva."),
     ],
     "margin": (("Structure decides which deals can close. Fit decides which ones are worth closing.",
                 "La estructura decide qué negocios pueden cerrarse. El encaje decide cuáles vale la pena cerrar."),)},
    {"slug": "assumptions-cost-six-figures",
     "date": ("March 2026", "marzo 2026"),
     "title": ("Assumptions cost six figures", "Los supuestos cuestan seis cifras"),
     "story": [
         ("The most dangerous week in a deal is the one right after the contract is signed. That is when people relax.",
          "La semana más peligrosa de un negocio es la que viene justo después de firmar el contrato. Ahí es cuando la gente se relaja."),
         ("I have learned to push harder then.", "Aprendí a empujar más fuerte justo entonces."),
         ("Soil. Topography. Flood plains. The deed restrictions, read myself, not summarised for me.",
          "El suelo. La topografía. Las zonas inundables. Las restricciones de la escritura, leídas por mí, no resumidas para mí."),
         ("One outdated plat can freeze a closing. One utility line hit without calling 811 can stop a site for weeks.",
          "Un plano desactualizado puede congelar un cierre. Una línea de servicios dañada sin llamar antes al 811 puede detener una obra durante semanas."),
         ("None of it is dramatic. It is details, communication and verification, done before they turn into a crisis.",
          "Nada de eso es dramático. Son detalles, comunicación y verificación, hechos antes de que se vuelvan crisis."),
     ],
     "margin": (("Hire someone to find the discrepancy, not to process the paperwork.",
                 "Contrata a alguien para encontrar la discrepancia, no para tramitar los papeles."),)},
    {"slug": "silence-is-thinking-space",
     "date": ("March 2026", "marzo 2026"),
     "title": ("Silence is thinking space", "El silencio es espacio para pensar"),
     "story": [
         ("I used to fill every pause when I spoke.", "Antes llenaba cada pausa cuando hablaba."),
         ("The problem was never that I talked too much. I was speaking before the thought had finished forming.",
          "El problema nunca fue que hablara demasiado. Hablaba antes de que la idea terminara de formarse."),
         ("Now I give the thought a frame before it leaves: what is interesting here, why it matters, and what should happen next.",
          "Ahora le doy un marco a la idea antes de que salga: qué es lo interesante, por qué importa y qué debería pasar después."),
         ("And I let the silence last a little longer than is comfortable. It is not empty. Something is still being decided in it.",
          "Y dejo que el silencio dure un poco más de lo cómodo. No está vacío. Ahí todavía se está decidiendo algo."),
     ]},
    {"slug": "the-deal-that-fell-through",
     "date": ("February 2026", "febrero 2026"),
     "title": ("The deal that fell through", "El negocio que se cayó"),
     "story": [
         ("A subdivision I was analysing fell through during due diligence. I spent weeks taking it apart.",
          "Una subdivisión que yo estaba analizando se cayó durante la debida diligencia. Pasé semanas desarmándola."),
         ("It was not one mistake. It was an assumption about zoning and infrastructure we had not validated, and a question of timing nobody wanted to name.",
          "No fue un solo error. Fue un supuesto sobre zonificación e infraestructura que no habíamos validado, y un problema de tiempos que nadie quería nombrar."),
         ("What one market calls undevelopable, another calls an opportunity.", "Lo que un mercado llama inedificable, otro lo llama oportunidad."),
         ("I wrote down what the market had actually told us, and what I would check first next time.",
          "Anoté lo que el mercado nos había dicho de verdad, y lo que revisaría primero la próxima vez."),
         ("I am still not sure the deal was wrong. Maybe it was only early.", "Todavía no estoy segura de que el negocio estuviera mal. Quizás solo era temprano."),
     ]},
    {"slug": "specific-beats-polite",
     "date": ("February 2026", "febrero 2026"),
     "title": ("Specific beats polite", "Lo concreto le gana a lo cortés"),
     "story": [
         ("Working across cultures, I caught myself softening a message so it would not feel uncomfortable.",
          "Trabajando entre culturas, me descubrí suavizando un mensaje para que no se sintiera incómodo."),
         ("It did not make it kinder. It made it confusing.", "No lo hizo más amable. Lo hizo confuso."),
         ("Mikael Krogerus changed what I thought clarity meant. Not simpler words. Concrete ones.",
          "Mikael Krogerus cambió lo que yo creía que significaba la claridad. No palabras más simples. Palabras concretas."),
         ("I still have to choose it every time. The comfortable sentence is always the easier one to say.",
          "Todavía tengo que elegirlo cada vez. La frase cómoda siempre es la más fácil de decir."),
     ]},
    {"slug": "made-of-concrete",
     "date": ("February 2026", "febrero 2026"),
     "title": ("Made of concrete", "Hecha de concreto"),
     "story": [
         ("There was a stretch when everything arrived at once. Tight deadlines. Incomplete information. Decisions that could not wait for clarity.",
          "Hubo una temporada en la que todo llegó al mismo tiempo. Plazos apretados. Información incompleta. Decisiones que no podían esperar a tener claridad."),
         ("Some people froze and waited for certainty. Others made the call with what they had.",
          "Algunas personas se congelaron y esperaron certezas. Otras tomaron la decisión con lo que tenían."),
         ("I did not know which one I was until there was no choice.", "No supe cuál era yo hasta que no hubo otra opción."),
         ("I build teams differently now. I notice who shows up when things get hard, not who sounds best when they are easy.",
          "Ahora armo los equipos de otra manera. Me fijo en quién aparece cuando las cosas se ponen difíciles, no en quién suena mejor cuando son fáciles."),
     ],
     "margin": (("Pressure does not create who we are. It shows it.", "La presión no crea quiénes somos. Lo revela."),)},
    {"slug": "two-engineers-same-degree",
     "date": ("February 2026", "febrero 2026"),
     "title": ("Two engineers, the same degree", "Dos ingenieros, el mismo título"),
     "story": [
         ("Two civil engineers. The same degree, the same years, the same technical skill. Very different salaries.",
          "Dos ingenieros civiles. El mismo título, los mismos años, las mismas habilidades técnicas. Salarios completamente diferentes."),
         ("We were trained to calculate structures, design projects and supervise sites. Nobody taught us to negotiate a contract, present a proposal clearly, or read a margin.",
          "Nos formaron para calcular estructuras, diseñar proyectos y supervisar obra. Nadie nos enseñó a negociar contratos, presentar propuestas con claridad o entender márgenes."),
         ("The market pays for what you know, but also for how clearly you can show the value it creates.",
          "El mercado paga por lo que sabes, pero también por qué tan claramente puedes mostrar el valor que generas."),
         ("Many times you do not need to change careers. You need to change how you stand inside the one you have.",
          "Muchas veces no necesitamos cambiar de carrera. Necesitamos cambiar cómo nos presentamos en la que tenemos."),
     ]},
    {"slug": "you-just-divide-up-land",
     "date": ("November 2025", "noviembre 2025"),
     "title": ("“You just divide up land and sell it, right?”", "“Solo divides la tierra y la vendes, ¿no?”"),
     "story": [
         ("Someone asked me that, half joking.", "Alguien me lo preguntó, medio en broma."),
         ("Not quite. Before a single lot exists there are engineers, surveyors, utility companies and county departments, each holding a piece of it.",
          "No exactamente. Antes de que exista un solo lote hay ingenieros, topógrafos, empresas de servicios y oficinas del condado, cada uno con una parte."),
         ("Drainage. Access. A regulation that changes at the county line. A street that has to make sense for families who have not arrived yet.",
          "El drenaje. El acceso. Una norma que cambia en el límite del condado. Una calle que tiene que tener sentido para familias que todavía no han llegado."),
         ("Every line on the plat is a decision somebody had to defend.", "Cada línea del plano es una decisión que alguien tuvo que defender."),
     ]},
    # moved from Inside My Mind (her ask, 2026-09): the land notes and the quote she keeps
    {"slug": "notes-on-land",
     "date": ("Notes · 2026", "Notas · 2026"),
     "title": ("Notes on land", "Notas sobre la tierra"),
     "story": [
         ("A field is never empty. It is waiting for a reason.", "Un terreno nunca está vacío. Está esperando una razón."),
         ("I read the road before the parcel. The road decides more than the price does.", "Leo la vía antes que el lote. La vía decide más que el precio."),
         ("Water, access, the neighbours. The drawing comes last.", "El agua, el acceso, los vecinos. El dibujo va de último."),
     ],
     "margin": (("“It is because nothing stays that the world is lovely.”", "“Es porque nada permanece que el mundo es hermoso.”"),
                ("Yoshida Kenkō · Essays in Idleness · c. 1330", "Yoshida Kenkō · Tsurezuregusa · c. 1330"))},
]
