"""Her About story — her words, with Spanish. Edit here, then run tools/build.py.

HOOK and INTRO sit beside her photograph. A chapter is (title EN, title ES, items).
An item is a line (en, es); a list of lines is a run-on list; ("PULL", en, es) is a
pull line, set large between hairlines.
"""
HOOK = ("I kept becoming responsible for the thing behind the thing.",
        "Siempre terminaba a cargo de lo que había detrás de las cosas.")

INTRO = [
 ("I studied civil engineering at Universidad Cooperativa de Colombia.", "Estudié ingeniería civil en la Universidad Cooperativa de Colombia."),
 ("An international engineering scholarship took me to Bilbao for a year, to the University of the Basque Country. That is where I began my thesis: an aerodrome for domestic flights.", "Una beca internacional de ingeniería me llevó a Bilbao por un año, a la Universidad del País Vasco. Allí empecé mi tesis: un aeródromo para vuelos nacionales."),
 ("At the time, I thought I was learning how things stood up.", "En ese momento, creía que estaba aprendiendo cómo se sostienen las cosas."),
 [("Loads.", "Cargas."), ("Materials.", "Materiales."), ("Plans.", "Planos."), ("Soil.", "Suelo."), ("Structure.", "Estructura.")],
 ("I did not know yet how often I would use that training on things with no concrete in them.", "Todavía no sabía cuántas veces usaría esa formación en cosas sin una gota de concreto."),
 [("A team.", "Un equipo."), ("A process.", "Un proceso."), ("A business.", "Un negocio."), ("A decision.", "Una decisión.")],
]

STORY = [
 ("Other rooms", "Otras salas", [
  ("Before development, there were other rooms.", "Antes del desarrollo, hubo otras salas."),
  [("An international engineering scholarship.", "Una beca internacional de ingeniería."),
   ("A year at the University of the Basque Country, in Bilbao.", "Un año en la Universidad del País Vasco, en Bilbao."),
   ("The first lines of my thesis.", "Las primeras líneas de mi tesis.")],
  ("Engineering was the reason I arrived.", "La ingeniería fue la razón por la que llegué."),
  ("Language changed what I noticed once I was there.", "El idioma cambió lo que notaba una vez allí."),
  [("A classroom where I also taught English.", "Un salón donde también enseñé inglés."), ("Customer support.", "Atención al cliente."),
   ("A grocery store in Utah during a summer abroad.", "Un supermercado en Utah durante un verano en el extranjero.")],
  [("Different accents.", "Acentos distintos."), ("Different systems.", "Sistemas distintos."),
   ("Different ways people asked for the same thing.", "Formas distintas de pedir lo mismo.")],
  ("Those years made me more international before I had language for it.", "Esos años me hicieron más internacional antes de que tuviera palabras para decirlo."),
  ("I learned to adapt quickly. To listen carefully. To work across cultures. To notice that the same problem can look completely different depending on who is standing in front of it.",
   "Aprendí a adaptarme rápido. A escuchar con cuidado. A trabajar entre culturas. A notar que el mismo problema puede verse completamente distinto según quién esté frente a él."),
 ]),
 ("Miami", "Miami", [
  ("I entered property management from the ground level.", "Entré a la administración de propiedades desde abajo."),
  ("I started as the property manager’s assistant.", "Empecé como asistente del administrador de propiedades."),
  ("Close to the everyday machinery.", "Cerca de la maquinaria de todos los días."),
  [("Tenants.", "Inquilinos."), ("Maintenance.", "Mantenimiento."), ("Vendors.", "Proveedores."), ("Follow-ups.", "Seguimientos.")],
  ("The small things that decide whether an operation actually works.", "Las cosas pequeñas que deciden si una operación funciona de verdad."),
  ("Then the scope widened.", "Después, el alcance se amplió."),
  ("I moved into project management.", "Pasé a la gestión de proyectos."),
  [("Construction.", "Construcción."), ("Capital improvements.", "Mejoras de capital."), ("Contractors.", "Contratistas."),
   ("MEP coordination.", "Coordinación MEP."), ("Plumbing.", "Plomería."), ("HVAC.", "Climatización.")],
  ("Active sites where a drawing eventually had to become pipe, ductwork, equipment, drywall, and somebody’s apartment again.",
   "Obras activas donde un plano tarde o temprano tenía que convertirse en tubería, ductos, equipos, drywall y otra vez en el apartamento de alguien."),
  ("I began looking at buildings differently.", "Empecé a mirar los edificios de otra manera."),
  [("Not only as properties to operate.", "No solo como propiedades que operar."), ("As assets.", "Como activos.")],
  [("Investors sat on one side of the table.", "Los inversionistas se sentaban a un lado de la mesa."), ("Buildings sat on the other.", "Los edificios, al otro.")],
  ("Between them were rents, vacancies, maintenance, construction, budgets, and hundreds of decisions that eventually appeared as return.",
   "Entre ellos había rentas, vacantes, mantenimiento, construcción, presupuestos y cientos de decisiones que al final aparecían como retorno."),
  ("PULL", "Multifamily taught me to look at a building twice.", "El multifamiliar me enseñó a mirar un edificio dos veces."),
  [("Once as a place.", "Una vez como lugar."), ("Then as an investment.", "Luego como inversión.")],
  [("A unit could be redesigned.", "Una unidad podía rediseñarse."), ("A repair could become preventive work.", "Una reparación podía volverse trabajo preventivo."),
   ("An expense could expose a larger operating problem.", "Un gasto podía revelar un problema operativo mayor."),
   ("A property that looked stable on paper could still be leaving value on the table.", "Una propiedad que se veía estable en papel podía estar dejando valor sobre la mesa.")],
  ("I started looking for those gaps.", "Empecé a buscar esas brechas."),
  [("What actually improves the asset.", "Qué mejora de verdad el activo."), ("What is cosmetic.", "Qué es cosmético."),
   ("What creates a better resident experience.", "Qué crea una mejor experiencia para el residente."),
   ("What strengthens the investment at the same time.", "Qué fortalece la inversión al mismo tiempo.")],
  ("ROI became less abstract when I could walk through the thing producing it.", "El retorno se volvió menos abstracto cuando podía caminar por lo que lo producía."),
  ("Construction sharpened that thinking.", "La construcción afinó esa forma de pensar."),
  [("A line on a plan can look perfect until it meets an existing wall.", "Una línea en un plano puede verse perfecta hasta que se encuentra con un muro existente."),
   ("A schedule can look reasonable until one trade is waiting on another.", "Un cronograma puede verse razonable hasta que un oficio está esperando a otro."),
   ("A budget can look complete until the ceiling opens.", "Un presupuesto puede verse completo hasta que se abre el techo.")],
  ("I learned to move between those layers.", "Aprendí a moverme entre esas capas."),
  [("Tenant.", "Inquilino."), ("Contractor.", "Contratista."), ("Building.", "Edificio."), ("Investor.", "Inversionista."), ("Return.", "Retorno.")],
  ("None of them existed separately.", "Ninguna existía por separado."),
  ("By the end of my time there, I was managing the company.", "Al final de mi tiempo ahí, estaba dirigiendo la empresa."),
  ("That changed the scale of the problem again.", "Eso volvió a cambiar la escala del problema."),
  [("It was no longer only about moving projects forward.", "Ya no se trataba solo de sacar proyectos adelante."),
   ("It was about building the operation around them.", "Se trataba de construir la operación a su alrededor.")],
  [("People.", "Personas."), ("Departments.", "Departamentos."), ("Accountability.", "Responsabilidad."), ("Information.", "Información."),
   ("Investor relationships.", "Relaciones con inversionistas."), ("Investment opportunities.", "Oportunidades de inversión."),
   ("The systems that allowed everything else to move.", "Los sistemas que permitían que todo lo demás se moviera.")],
  ("Somewhere in that period, project management stopped meaning “keep the project on schedule.”", "En algún momento de esa etapa, gestionar proyectos dejó de significar “mantener el proyecto a tiempo”."),
  ("PULL", "It became the work of seeing enough of the whole system to change the outcome before the problem became expensive.",
   "Se volvió el trabajo de ver lo suficiente del sistema completo para cambiar el resultado antes de que el problema saliera caro."),
 ]),
 ("Then land arrived", "Luego llegó la tierra", [
  ("At Scout Land Group, the scale changed.", "En Scout Land Group, la escala cambió."),
  [("A road at one edge.", "Una vía en un borde."), ("A title exception.", "Una excepción en el título."), ("A county ordinance.", "Una ordenanza del condado."),
   ("A broker’s opinion.", "La opinión de un corredor."), ("A subdivision that did not exist yet.", "Una subdivisión que todavía no existía.")],
  ("I began in project management and underwriting and gradually moved further upstream.", "Empecé en gestión de proyectos y análisis, y poco a poco fui subiendo hacia el origen de las decisiones."),
  [("Markets.", "Mercados."), ("Feasibility.", "Factibilidad."), ("Transactions.", "Transacciones."), ("Broker opinions of value.", "Opiniones de valor de corredores."),
   ("Development.", "Desarrollo."), ("The teams and systems behind those decisions.", "Los equipos y sistemas detrás de esas decisiones.")],
  ("PULL", "Today I lead development and underwriting.", "Hoy lidero desarrollo y análisis."),
 ]),
 ("What has to be true", "Lo que tiene que ser cierto", [
  ("I still like the moment before the answer becomes obvious.", "Todavía me gusta el momento antes de que la respuesta sea obvia."),
  [("I want to know what has to be true.", "Quiero saber qué tiene que ser cierto."), ("What is missing.", "Qué falta."),
   ("What changes if one assumption moves.", "Qué cambia si un supuesto se mueve."), ("What should be automated.", "Qué debería automatizarse."),
   ("What should stay human.", "Qué debería seguir siendo humano.")],
  ("That last distinction matters to me.", "Esa última distinción me importa."),
  ("I love automation because it can return attention to the places where judgment, creativity, negotiation, and relationships still matter.",
   "Me encanta automatizar porque devuelve la atención a los lugares donde el criterio, la creatividad, la negociación y las relaciones todavía importan."),
  [("A good system is a multiplier.", "Un buen sistema es un multiplicador."), ("So is the right person.", "También lo es la persona correcta."),
   ("So is clear ownership.", "También la responsabilidad clara."),
   ("So is a team that knows how to move without waiting for permission at every step.", "También un equipo que sabe moverse sin esperar permiso a cada paso.")],
  ("A large part of my work has become building those multipliers.", "Gran parte de mi trabajo se ha vuelto construir esos multiplicadores."),
  [("Sometimes the model.", "A veces el modelo."), ("Sometimes the workflow.", "A veces el flujo de trabajo."), ("Sometimes the team.", "A veces el equipo."),
   ("Sometimes the department around it.", "A veces el departamento que lo rodea.")],
  ("PULL", "The goal is not more activity. It is better leverage.", "La meta no es más actividad. Es mejor apalancamiento."),
 ]),
 ("Buildings", "Edificios", [
  ("That same way of thinking follows me outside of work.", "Esa misma forma de pensar me sigue fuera del trabajo."),
  ("I can spend hours looking at a building.", "Puedo pasar horas mirando un edificio."),
  [("Not only the facade.", "No solo la fachada."), ("The section behind it.", "El corte detrás de ella."), ("The staircase.", "La escalera."), ("The material joint.", "La junta entre materiales.")],
  ("The place where somebody had to turn a drawing into concrete, steel, wood and glass.", "El lugar donde alguien tuvo que convertir un dibujo en concreto, acero, madera y vidrio."),
  ("PULL", "Construction fascinates me because eventually an idea has to answer to reality.", "La construcción me fascina porque, tarde o temprano, una idea tiene que responderle a la realidad."),
  ("Architecture asks what it feels like once it stands.", "La arquitectura pregunta cómo se siente una vez en pie."),
  [("Light.", "Luz."), ("Proportion.", "Proporción."), ("Texture.", "Textura."), ("The distance between things.", "La distancia entre las cosas.")],
  [("Why one room makes you slow down.", "Por qué una habitación te hace ir más despacio."), ("Why another does not.", "Por qué otra no.")],
  ("I notice those things.", "Yo noto esas cosas."),
 ]),
 ("Art", "Arte", [
  ("I notice them in art too.", "También las noto en el arte."),
  [("A brushstroke.", "Una pincelada."), ("An old map.", "Un mapa antiguo."), ("A botanical plate.", "Una lámina botánica."), ("A gemstone.", "Una gema."),
   ("A piece of jewelry where proportion matters more than size.", "Una joya donde la proporción importa más que el tamaño.")],
  ("Objects become more interesting to me when I understand how they were made.", "Los objetos me interesan más cuando entiendo cómo fueron hechos."),
 ]),
 ("Languages and places", "Idiomas y lugares", [
  ("Languages do something similar.", "Los idiomas hacen algo parecido."),
  ("I learn them because culture changes when it stops arriving entirely through translation.", "Los aprendo porque la cultura cambia cuando deja de llegar solo a través de la traducción."),
  [("A joke lands differently.", "Un chiste cae distinto."), ("A song opens.", "Una canción se abre."),
   ("A street sign becomes a sentence instead of a shape.", "Un letrero se vuelve una frase en lugar de una forma.")],
  ("You begin to understand what people soften, what they exaggerate, what they find beautiful, what they leave unsaid.",
   "Empiezas a entender qué suaviza la gente, qué exagera, qué le parece bello, qué deja sin decir."),
  ("That is one of the reasons I love moving through different countries and cultures.", "Esa es una de las razones por las que me encanta moverme entre países y culturas."),
  [("I am interested in how people build.", "Me interesa cómo construye la gente."), ("How they speak.", "Cómo habla."), ("How they use space.", "Cómo usa el espacio."),
   ("What they preserve.", "Qué conserva."), ("What they replace.", "Qué reemplaza."), ("What they consider ordinary.", "Qué considera normal.")],
  ("I like old streets, museums, markets, gardens, construction sites, unfamiliar neighborhoods, and the moment when a place starts making sense on its own terms.",
   "Me gustan las calles antiguas, los museos, los mercados, los jardines, las obras, los barrios desconocidos y el momento en que un lugar empieza a tener sentido en sus propios términos."),
 ]),
 ("Drawing", "Dibujo", [
  ("Drawing brings me back to the same habit.", "Dibujar me devuelve al mismo hábito."),
  [("Look first.", "Mirar primero."), ("Assume less.", "Suponer menos.")],
  [("A stem does not bend where memory expects it to.", "Un tallo no se dobla donde la memoria espera."), ("A leaf is rarely symmetrical.", "Una hoja casi nunca es simétrica."),
   ("A shadow changes the structure.", "Una sombra cambia la estructura.")],
  [("Critical thinking works much the same way.", "El pensamiento crítico funciona casi igual."), ("So does creativity.", "La creatividad también.")],
  ("I do not see them as opposites anymore.", "Ya no las veo como opuestos."),
  ("The analytical side wants the idea to survive scrutiny.", "El lado analítico quiere que la idea sobreviva al escrutinio."),
  ("The creative side looks for the route nobody tried yet.", "El lado creativo busca la ruta que nadie ha probado."),
  ("I need both.", "Necesito los dos."),
 ]),
 ("How it connects", "Cómo se conecta", [
  ("There are parts of my career that would have looked impossible to connect while I was living them.", "Hay partes de mi carrera que habría sido imposible conectar mientras las vivía."),
  [("An engineering classroom in Colombia.", "Un salón de ingeniería en Colombia."), ("An engineering scholarship in Spain.", "Una beca de ingeniería en España."),
   ("A grocery aisle in Utah.", "Un pasillo de supermercado en Utah."), ("A property operation in Miami.", "Una operación de propiedades en Miami."),
   ("A subdivision plat somewhere in the United States.", "El plano de una subdivisión en algún lugar de Estados Unidos."),
   ("A workflow quietly running without the person who used to repeat it.", "Un flujo de trabajo corriendo en silencio sin la persona que antes lo repetía.")],
  ("They connect now.", "Ahora se conectan."),
  [("Not because they were planned that way.", "No porque lo hubiera planeado así."),
   ("Because each one taught me how to look at the next thing differently.", "Sino porque cada una me enseñó a mirar lo siguiente de otra manera.")],
  ("I still keep learning things that do not seem to belong together.", "Sigo aprendiendo cosas que no parecen ir juntas."),
  [("Art.", "Arte."), ("Languages.", "Idiomas."), ("Construction.", "Construcción."), ("Technology.", "Tecnología."), ("Money.", "Dinero."),
   ("Plants.", "Plantas."), ("Music.", "Música."), ("Architecture.", "Arquitectura."), ("Development.", "Desarrollo.")],
  [("Sometimes they stay separate.", "A veces se quedan separadas."), ("Sometimes two of them meet and something new appears.", "A veces dos se encuentran y aparece algo nuevo.")],
  ("PULL", "There is usually another line to follow.", "Casi siempre hay otra línea que seguir."),
 ]),
]
