"""Her story, for the About page — her words, in short lines, with Spanish.

A chapter is (title EN, title ES, items). An item is a line (en, es), or a list
of lines that belong together and are set as a stack.
"""
OPENING = [
    ("A drawing, a building, a sentence in another language.", "Un dibujo, un edificio, una frase en otro idioma."),
    ("I usually want to know what is underneath.", "Casi siempre quiero saber qué hay debajo."),
]

STORY = [
 ("Curiosity", "Curiosidad", [
  ("I have always been curious in a way that rarely stays inside one subject.", "Siempre he sido curiosa de una forma que casi nunca se queda en un solo tema."),
  ("I can spend the morning thinking about a development problem and the afternoon looking at why one facade feels balanced and another does not.", "Puedo pasar la mañana pensando en un problema de desarrollo y la tarde mirando por qué una fachada se siente equilibrada y otra no."),
  ("I can disappear into a workflow until I understand how to automate it.", "Puedo perderme en un flujo de trabajo hasta entender cómo automatizarlo."),
  ("Then lose an unreasonable amount of time looking at an orchid root.", "Y luego perder una cantidad irrazonable de tiempo mirando la raíz de una orquídea."),
  ("It makes sense to me.", "Para mí tiene sentido."),
  ("I like understanding how things are put together.", "Me gusta entender cómo están hechas las cosas."),
  [("A building.", "Un edificio."), ("A business.", "Un negocio."), ("A team.", "Un equipo."), ("A financial model.", "Un modelo financiero."),
   ("A language.", "Un idioma."), ("A piece of jewelry.", "Una joya."), ("A culture.", "Una cultura."), ("A drawing.", "Un dibujo.")],
  [("The questions change.", "Las preguntas cambian."), ("The instinct does not.", "El instinto no.")],
  [("I look closely.", "Miro de cerca."), ("I pull things apart.", "Desarmo las cosas."),
   ("I try to understand which pieces actually matter.", "Intento entender qué piezas importan de verdad."), ("Then I start moving them.", "Luego empiezo a moverlas.")],
 ]),
 ("Problems", "Problemas", [
  ("That is probably why problem solving has become such a large part of my life.", "Probablemente por eso resolver problemas se ha vuelto una parte tan grande de mi vida."),
  ("I like problems with more than one correct-looking answer.", "Me gustan los problemas con más de una respuesta que parece correcta."),
  ("The analytical part of me wants evidence.", "La parte analítica de mí quiere evidencia."),
  [("What do we know.", "Qué sabemos."), ("What are we assuming.", "Qué estamos suponiendo."),
   ("What happens if that assumption moves.", "Qué pasa si ese supuesto se mueve."), ("What does not reconcile.", "Qué no cuadra.")],
  ("The creative part is less obedient.", "La parte creativa es menos obediente."),
  ("It wants to try another route.", "Quiere probar otra ruta."),
  [("Change the sequence.", "Cambiar el orden."), ("Remove the step.", "Quitar el paso."),
   ("Combine two things that were never designed to work together.", "Combinar dos cosas que nunca se diseñaron para funcionar juntas."),
   ("Turn the problem around and look at it from somewhere else.", "Darle la vuelta al problema y mirarlo desde otro lugar.")],
  ("I need both.", "Necesito las dos."),
  ("Creativity without scrutiny can produce an interesting bad idea.", "La creatividad sin escrutinio puede producir una mala idea interesante."),
  ("Analysis without imagination can produce the safest version of something that should have been better.", "El análisis sin imaginación puede producir la versión más segura de algo que debió ser mejor."),
  [("I like the space between them.", "Me gusta el espacio entre las dos."), ("That is where most of my work happens.", "Ahí ocurre la mayor parte de mi trabajo.")],
 ]),
 ("Construction and architecture", "Construcción y arquitectura", [
  ("Sometimes the problem is physical.", "A veces el problema es físico."),
  [("A site.", "Un terreno."), ("A road.", "Una vía."), ("A building detail.", "Un detalle constructivo.")],
  ("Something that eventually has to survive concrete, water, gravity, labor and time.", "Algo que tarde o temprano tiene que sobrevivir al concreto, el agua, la gravedad, la mano de obra y el tiempo."),
  ("My engineering background probably explains some of my fascination with construction.", "Mi formación de ingeniera probablemente explica parte de mi fascinación por la construcción."),
  ("I love the moment when a drawing stops being theoretical.", "Me encanta el momento en que un dibujo deja de ser teórico."),
  [("A line becomes a wall.", "Una línea se vuelve un muro."), ("A dimension becomes a room.", "Una medida se vuelve una habitación."),
   ("A material choice changes the temperature of a space.", "La elección de un material cambia la temperatura de un espacio.")],
  ("Someone resolves a detail on site that almost nobody will ever notice once the building is finished.", "Alguien resuelve en obra un detalle que casi nadie notará cuando el edificio esté terminado."),
  ("I notice those things.", "Yo noto esas cosas."),
  ("Architecture gives me the other half.", "La arquitectura me da la otra mitad."),
  [("Construction asks whether it can stand.", "La construcción pregunta si puede sostenerse."),
   ("Architecture asks what it feels like to be there.", "La arquitectura pregunta cómo se siente estar ahí.")],
  [("Light coming through a window.", "La luz entrando por una ventana."), ("Stone that has aged well.", "Una piedra que ha envejecido bien."),
   ("A staircase proportioned just right.", "Una escalera con la proporción justa."), ("The distance between two buildings.", "La distancia entre dos edificios."),
   ("A courtyard that makes you stay five minutes longer than you intended.", "Un patio que te hace quedarte cinco minutos más de lo que pensabas.")],
  ("I can look at those things for a long time.", "Puedo mirar esas cosas durante mucho tiempo."),
 ]),
 ("Systems and teams", "Sistemas y equipos", [
  ("I do the same with systems.", "Hago lo mismo con los sistemas."),
  ("When a process is repetitive, confusing or dependent on someone remembering the next step, I start seeing its structure.", "Cuando un proceso es repetitivo, confuso o depende de que alguien recuerde el siguiente paso, empiezo a ver su estructura."),
  [("Where does information enter.", "Por dónde entra la información."), ("Where does it get lost.", "Dónde se pierde."),
   ("Who is making the decision.", "Quién toma la decisión."), ("Who should be making it.", "Quién debería tomarla."),
   ("What part actually requires judgment.", "Qué parte requiere criterio de verdad."),
   ("What part is just repetition pretending to be work.", "Qué parte es solo repetición haciéndose pasar por trabajo.")],
  ("I love automation because it lets me separate the two.", "Me encanta automatizar porque me permite separar las dos."),
  [("Let the system carry the mechanical part.", "Que el sistema cargue con la parte mecánica."),
   ("Keep the person where judgment still matters.", "Y que la persona se quede donde el criterio todavía importa.")],
  ("The same is true when I build teams.", "Lo mismo pasa cuando formo equipos."),
  ("I like watching a group of people become something more coherent than a collection of job descriptions.", "Me gusta ver cómo un grupo de personas se vuelve algo más coherente que una colección de descripciones de cargo."),
  [("Clear ownership changes people.", "La responsabilidad clara cambia a las personas."), ("Trust changes speed.", "La confianza cambia la velocidad."),
   ("The right person in the right place changes the capacity of an entire department.", "La persona correcta en el lugar correcto cambia la capacidad de todo un departamento."),
   ("A good system does too.", "Un buen sistema también.")],
  ("I think often about multiplier forces.", "Pienso mucho en las fuerzas multiplicadoras."),
  [("Not how to squeeze more work out of someone.", "No en cómo sacarle más trabajo a alguien."),
   ("How to make good judgment travel further.", "Sino en cómo hacer que el buen criterio llegue más lejos.")],
  [("A better process.", "Un mejor proceso."), ("A stronger person.", "Una persona más fuerte."), ("Clearer context.", "Un contexto más claro."),
   ("Technology.", "La tecnología."), ("A team that knows where it is going.", "Un equipo que sabe hacia dónde va."),
   ("One good decision that removes ten future problems.", "Una buena decisión que elimina diez problemas futuros.")],
  ("That is much more interesting to me than being busy.", "Eso me interesa mucho más que estar ocupada."),
 ]),
 ("Art and beauty", "Arte y belleza", [
  ("Away from work, my curiosity becomes less useful and probably more revealing.", "Lejos del trabajo, mi curiosidad se vuelve menos útil y probablemente más reveladora."),
  ("I love art because it gives me something I cannot reduce completely.", "Amo el arte porque me da algo que no puedo reducir del todo."),
  ("A painting can be technically explained and still refuse to be exhausted by the explanation.", "Una pintura puede explicarse técnicamente y aun así negarse a quedar agotada por la explicación."),
  ("I like that.", "Eso me gusta."),
  [("I like old maps.", "Me gustan los mapas antiguos."), ("Botanical drawings.", "Los dibujos botánicos."), ("Jewelry.", "Las joyas."),
   ("Photography.", "La fotografía."), ("Music.", "La música."), ("Buildings with evidence of time on them.", "Los edificios con huellas del tiempo.")],
  ("Objects where somebody cared about the line, the proportion, the material, even when doing so was unnecessary.", "Los objetos en los que alguien cuidó la línea, la proporción y el material, incluso cuando no era necesario."),
  [("Craftsmanship gets my attention quickly.", "El oficio bien hecho capta mi atención enseguida."), ("So does beauty.", "La belleza también.")],
  [("But I am rarely satisfied with simply calling something beautiful.", "Pero casi nunca me basta con decir que algo es bello."), ("I want to know why.", "Quiero saber por qué.")],
  [("Why does this color work.", "Por qué funciona este color."), ("Why does that room feel warm.", "Por qué esa habitación se siente cálida."),
   ("Why does one stone look alive and another look flat.", "Por qué una piedra parece viva y otra plana."),
   ("Why does this photograph feel cinematic.", "Por qué esta fotografía se siente cinematográfica."),
   ("Why does one object feel refined while another only feels expensive.", "Por qué un objeto se siente refinado y otro solo se siente caro.")],
  [("Sometimes I find an answer.", "A veces encuentro una respuesta."), ("Sometimes I just keep looking.", "A veces simplemente sigo mirando.")],
 ]),
 ("Languages and travel", "Idiomas y viajes", [
  ("Languages opened another part of that curiosity.", "Los idiomas abrieron otra parte de esa curiosidad."),
  ("I do not learn them only because I want to communicate.", "No los aprendo solo para comunicarme."),
  ("I like what a language reveals about the people who speak it.", "Me gusta lo que un idioma revela de quienes lo hablan."),
  [("What deserves its own word.", "Qué merece su propia palabra."), ("How affection is expressed.", "Cómo se expresa el cariño."),
   ("How formality works.", "Cómo funciona la formalidad."), ("What is softened.", "Qué se suaviza."), ("What is said directly.", "Qué se dice directamente."),
   ("What is funny.", "Qué da risa."), ("What sounds beautiful.", "Qué suena bonito."),
   ("What becomes awkward when translated literally.", "Qué se vuelve torpe al traducirse literalmente.")],
  ("Culture becomes much more interesting when it stops arriving entirely through English.", "La cultura se vuelve mucho más interesante cuando deja de llegar solo a través del inglés."),
  [("A song changes.", "Una canción cambia."), ("A conversation changes.", "Una conversación cambia."), ("A city changes.", "Una ciudad cambia."),
   ("Even silence starts to mean something different.", "Hasta el silencio empieza a significar otra cosa.")],
  ("That is one of the reasons I love traveling.", "Esa es una de las razones por las que me encanta viajar."),
  ("I want to know how other people arrange ordinary life.", "Quiero saber cómo organizan otras personas la vida de todos los días."),
  [("How they eat.", "Cómo comen."), ("How they build.", "Cómo construyen."), ("How they use public space.", "Cómo usan el espacio público."),
   ("What they preserve.", "Qué conservan."), ("What they replace.", "Qué reemplazan."), ("What they wear.", "Qué se ponen."),
   ("How they speak to strangers.", "Cómo les hablan a los desconocidos."), ("What they consider tasteful.", "Qué consideran de buen gusto."),
   ("What they consider too much.", "Qué consideran demasiado.")],
  [("I like cities that let you see several centuries at once.", "Me gustan las ciudades que dejan ver varios siglos a la vez."),
   ("I like landscapes that make buildings feel very small.", "Me gustan los paisajes que hacen que los edificios parezcan muy pequeños."),
   ("I like arriving somewhere without knowing enough yet.", "Me gusta llegar a un lugar sin saber todavía lo suficiente.")],
  ("There is freedom in being a beginner.", "Hay libertad en ser principiante."),
 ]),
 ("Learning", "Aprender", [
  ("I have always liked learning.", "Siempre me ha gustado aprender."),
  [("Not collecting information.", "No acumular información."),
   ("Learning something until it starts changing the way I notice things.", "Aprender algo hasta que empieza a cambiar la forma en que noto las cosas.")],
  [("A book about money changes how I see ownership.", "Un libro sobre dinero cambia cómo veo la propiedad."),
   ("A language changes how I hear a conversation.", "Un idioma cambia cómo escucho una conversación."),
   ("Engineering changes how I look at a bridge.", "La ingeniería cambia cómo miro un puente."),
   ("Drawing changes how I look at a leaf.", "Dibujar cambia cómo miro una hoja."),
   ("Understanding construction changes how I enter a building.", "Entender la construcción cambia cómo entro a un edificio."),
   ("Learning about gemstones makes it impossible to see jewelry the same way again.", "Aprender sobre gemas hace imposible volver a ver las joyas igual.")],
  [("Once I know more, the world gets more detailed.", "Cuando sé más, el mundo se vuelve más detallado."), ("I like that feeling.", "Me gusta esa sensación.")],
 ]),
 ("Drawing, plants, music", "Dibujo, plantas, música", [
  ("Drawing has become one of the quieter versions of it.", "Dibujar se ha vuelto una de sus versiones más silenciosas."),
  ("You cannot draw something carefully without discovering that your memory of it was wrong.", "No puedes dibujar algo con cuidado sin descubrir que lo recordabas mal."),
  [("The stem bends somewhere else.", "El tallo se dobla en otro lugar."), ("The petal overlaps differently.", "El pétalo se superpone de otra manera."),
   ("The shadow carries more shape than you noticed.", "La sombra tiene más forma de la que habías notado.")],
  [("It forces me to slow down.", "Me obliga a ir más despacio."), ("Plants do too.", "Las plantas también.")],
  [("I can be impatient almost everywhere else.", "Puedo ser impaciente casi en todo lo demás."), ("Plants are unimpressed.", "A las plantas no les impresiona.")],
  ("An orchid does not care about the speed of my calendar.", "A una orquídea no le importa la velocidad de mi agenda."),
  ("Something can appear completely still while a root is growing underneath.", "Algo puede parecer completamente quieto mientras una raíz crece debajo."),
  [("There is probably a lesson there.", "Probablemente ahí hay una lección."), ("I am still learning it.", "Todavía la estoy aprendiendo.")],
  ("Music gives me something different.", "La música me da algo distinto."),
  ("There is no shortcut around practice.", "No hay atajo para la práctica."),
  [("You can understand what your hands are supposed to do and still not be able to do it.", "Puedes entender lo que deben hacer tus manos y aun así no lograrlo."),
   ("Then one day they can.", "Hasta que un día lo logran.")],
  [("I like disciplines that humble intelligence a little.", "Me gustan las disciplinas que le bajan un poco los humos a la inteligencia."),
   ("They make you earn the physical part.", "Te obligan a ganarte la parte física.")],
 ]),
 ("Money", "Dinero", [
  ("Money interests me in a different way than it used to.", "El dinero me interesa de una forma distinta a la de antes."),
  [("Less as consumption.", "Menos como consumo."), ("More as architecture.", "Más como arquitectura.")],
  [("How income becomes capital.", "Cómo el ingreso se vuelve capital."), ("How capital becomes ownership.", "Cómo el capital se vuelve propiedad."),
   ("How ownership creates options.", "Cómo la propiedad crea opciones."),
   ("How people build things that continue producing value after the original effort is over.", "Cómo la gente construye cosas que siguen produciendo valor cuando el esfuerzo original ya terminó.")],
  [("Lately I am learning to invest, and I love it.", "Últimamente estoy aprendiendo a invertir, y me encanta."),
   ("The market, and the potential I see in Colombia.", "El mercado, y el potencial que veo en Colombia.")],
  [("I like beautiful things.", "Me gustan las cosas bellas."), ("I also like knowing what they cost and why.", "También me gusta saber cuánto cuestan y por qué.")],
  ("Those two sides coexist quite peacefully in me.", "Esos dos lados conviven bastante en paz dentro de mí."),
 ]),
 ("The way I look", "Mi forma de mirar", [
  ("A lot of my life seems to work that way.", "Buena parte de mi vida parece funcionar así."),
  [("The practical and the romantic.", "Lo práctico y lo romántico."), ("The engineer and the artist.", "La ingeniera y la artista."),
   ("Automation and old maps.", "La automatización y los mapas antiguos."), ("Construction sites and orchids.", "Las obras y las orquídeas."),
   ("Financial models and jewelry.", "Los modelos financieros y las joyas."), ("Heavy guitar and botanical drawings.", "La guitarra pesada y los dibujos botánicos."),
   ("New technology and buildings older than everyone I know.", "La tecnología nueva y los edificios más viejos que todas las personas que conozco.")],
  ("For a while I thought having so many interests meant I had not chosen a lane.", "Durante un tiempo pensé que tener tantos intereses significaba que no había elegido un camino."),
  ("I think differently now.", "Ahora lo veo distinto."),
  [("The lane was never the subject.", "El camino nunca fue el tema."), ("It was the way I look.", "Era mi forma de mirar.")],
  [("I like structure.", "Me gusta la estructura."), ("I like beauty.", "Me gusta la belleza."), ("I like difficult problems.", "Me gustan los problemas difíciles."),
   ("I like people who think for themselves.", "Me gusta la gente que piensa por sí misma."),
   ("I like learning enough about something to stop seeing the obvious version of it.", "Me gusta aprender lo suficiente de algo como para dejar de ver su versión obvia."),
   ("I like building things that did not exist before.", "Me gusta construir cosas que antes no existían.")],
  [("Sometimes that is a development.", "A veces es un desarrollo."), ("Sometimes a department.", "A veces un departamento."),
   ("Sometimes a system.", "A veces un sistema."), ("Sometimes a drawing.", "A veces un dibujo."),
   ("Sometimes it is simply a better way of understanding something.", "A veces es simplemente una mejor manera de entender algo.")],
  [("I do not know what all of those lines become yet.", "Todavía no sé en qué se convierten todas esas líneas."),
   ("That is part of why I keep drawing them.", "En parte por eso las sigo dibujando.")],
 ]),
]
